---
ktor:
  development: true
  deployment:
    port: 8080
  application:
    modules:
      - com.ghkasra.discordclone.CallLoggingKt.configureCallLogging
      - com.ghkasra.discordclone.HttpKt.configureHttp
      - com.ghkasra.discordclone.SerializationKt.configureSerialization
      - com.ghkasra.discordclone.WebsocketsKt.configureWebsockets
      - com.ghkasra.discordclone.RoutingKt.configureRouting
